//Add Watch window Variables
expRemoveAll
expAdd("Gui_LightCommand",getQValue(13))
expAdd("Gui_Vpv",getQValue(9))
expAdd("Gui_Vboost",getQValue(9))
expAdd("Gui_Ipv",getQValue(12))
expAdd("Gui_PanelPower",getQValue(9))
expAdd("Gui_PanelPower_Theoretical",getQValue(9))
expAdd("ClearInvTrip",getNatural())
expAdd("InvModIndex",getQValue(24))
expAdd("VpvRef",getQValue(24))
expAdd("VpvRead",getQValue(24))
expAdd("MPPT_ENABLE",getNatural())
expAdd("Gui_InvStart",getNatural())
expAdd("Gui_InvStop",getNatural())
